# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
